# Generated by Django 2.0.2 on 2018-02-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCenterLogIN',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('IncidentType', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=50000)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
