# Generated by Django 2.0.2 on 2018-02-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Details',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
