# Generated by Django 2.0.2 on 2018-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0002_request_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('StationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('StationName', models.CharField(max_length=1000)),
                ('StationArea', models.CharField(max_length=1000)),
                ('Latitude', models.CharField(max_length=50)),
                ('Longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
